### ISSUE TITLE
First open source release

### ISSUE THREAD

**Issue by Briancbn** [ros-industrial/rmf_scheduler#1]
Using this thread to track the road to first open source release.

A few things to add before the first open source release (`0.2.4`).

Must have
- [x] CI, remove private dependencies. (#2, #4)
- [x] A few demo and examples. (#10)
- [x] ~API &~ simple usage documentation, README as well. (#5)
- [x] Merge in changes from 0.2.x from Gitlab. (#3)

**Comment by Briancbn** [comment]
Pending #12, waiting for `rmf_api_msgs` to make a release.

**Comment by Briancbn** [comment]
`0.2.4` is released.
